version: "3.7"
services:

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: letmein

  ipfs:
    image: ipfs/go-ipfs:v0.4.23
    ports:
      - '5001:5001'

  ganache:
    image: trufflesuite/ganache-cli:v6.9.1
    command: ganache-cli -d
    ports:
      - '8545:8545'

  graph-node:
    image: graphprotocol/graph-node:v0.19.0
    ports:
      - '8000:8000'
      - '8020:8020'
    environment:
      postgres_host: 'postgres'
      postgres_user: postgres
      postgres_pass: letmein
      postgres_db: postgres
      ipfs: 'ipfs:5001'
      ethereum: 'development:http://ganache:8545'
